/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modele;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author olivier
 */
public class ModifHospitalisation extends javax.swing.JFrame {

      static Connection conn = null;
    ResultSet rs = null ;
    PreparedStatement ps = null;
    static String test = null;
    int ok = 5;
    /**
     * Creates new form ModifHospitalisation
     * @param test
     * @param connexion
     */
    public ModifHospitalisation(String test, Connection connexion) {
       ModifHospitalisation.conn = connexion;
       initComponents();
       this.recuperer(test);
    }
    
    private void recuperer(String test){
       /* System.out.println("A");
        List_des_employes inf = new List_des_employes();
        System.out.println("B");
        inf.deplacement();
        System.out.println("C");*/
        try{
            
            String rec = test;
            String requete = "select * from HOSPITALISATION where no_malade ='"+rec+"'";
            
            ps =conn.prepareStatement(requete);
            rs = ps.executeQuery();
            if(rs.next()){
                String t1 = rs.getString("no_malade");
                txt_num.setText(t1);
                String t2 = rs.getString("code_service");
                txt_code.setText(t2);
                String t3 = rs.getString("no_chambre");
                txt_chbr.setText(t3);
                String t4 = rs.getString("lit");
                txt_lit.setText(t4);
            }
            
        }catch(SQLException e){
            System.out.println("Exeption" + e);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_lit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Modif = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_code = new javax.swing.JTextField();
        txt_num = new javax.swing.JTextField();
        txt_chbr = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setText("Code de Service :");

        Modif.setText("Modifier");
        Modif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifActionPerformed(evt);
            }
        });

        jLabel10.setText("n° chambre :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Hospitalisation :");

        jLabel8.setText("Numéro :");

        txt_num.setEditable(false);
        txt_num.setBorder(null);

        jLabel11.setText("n° lit :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_chbr, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(txt_lit))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txt_num, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txt_code, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Modif, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_chbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_lit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(Modif, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifActionPerformed
        String t1 = txt_num.getText();
        String t2 = txt_code.getText();
        String t4 = txt_chbr.getText();
        String t5 = txt_lit.getText();

        String requete = "update HOSPITALISATION set no_malade = '"+t1+"', code_service ='"+t2+"', no_chambre ='"+t4+"', lit ='"+t5+"' where no_malade = '"+t1+"'";
        try{
            
            ok =5;
            String var = txt_code.getText();
            String verif ="select * from SERVICE where code = '"+var+"'";
            
            ps = conn.prepareStatement(verif);
            rs =  ps.executeQuery();
            
            if(rs.next())
                ok--;
            else{
                JOptionPane.showMessageDialog(null,"Service non répertorié");
            }
            
            /////////////////////////////////////////////////////////////////////
            
            var = txt_chbr.getText();
            verif ="select * from CHAMBRE where no_chambre = '"+var+"'";
            
            ps = conn.prepareStatement(verif);
            rs =  ps.executeQuery();
            
            if(rs.next())
                ok--;
            else{
                JOptionPane.showMessageDialog(null,"Cette chambre n'a pas encore été construite");
            }
            
             /////////////////////////////////////////////////////////////////////
           
            
             /////////////////////////////////////////////////////////////////////
             
            var = txt_lit.getText();
            verif ="select * from CHAMBRE where '"+var+"' <= nb_lits";
            
            ps = conn.prepareStatement(verif);
            rs =  ps.executeQuery();
            
            if(rs.next())
                ok--;
            else{
                JOptionPane.showMessageDialog(null,"Pas assez de lits dans la chambre");
            }
            
             /////////////////////////////////////////////////////////////////////
             
             var = txt_lit.getText();
            verif ="select * from HOSPITALISATION where lit = '"+var+"' and no_chambre = '"+txt_chbr.getText()+"'";
            
            ps = conn.prepareStatement(verif);
            rs =  ps.executeQuery();
            
            if(rs.next())
                JOptionPane.showMessageDialog(null,"Lit déjà utilisé");
                
            else{
                ok--;                
            }
            
             /////////////////////////////////////////////////////////////////////
            if(ok == 0){
            ps = conn.prepareStatement(requete);
            ps.execute();
            JOptionPane.showMessageDialog(null,"Modifié avec succès");
            dispose();
            }

        }catch(SQLException e){
            System.out.println("Exeption" + e);
        }finally{
            try{
                ps.close();
            }catch(SQLException e){
                System.out.println("Exeption" + e);
            }
        }
    }//GEN-LAST:event_ModifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifHospitalisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifHospitalisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifHospitalisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifHospitalisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ModifHospitalisation(test, conn).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modif;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_chbr;
    private javax.swing.JTextField txt_code;
    private javax.swing.JTextField txt_lit;
    private javax.swing.JTextField txt_num;
    // End of variables declaration//GEN-END:variables
}
